// <auto-generated />
using System;
using GachiHelp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GachiHelp.WebApi.Migrations
{
    [DbContext(typeof(GachiContext))]
    [Migration("20221120150556_AddedProposedApplications")]
    partial class AddedProposedApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GachiHelp.DAL.Entities.AppliedJobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppliedUsersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppliedUsersId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("AppliedJobApplication");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.Help", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HelpCategoryId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("HelpCategoryId");

                    b.ToTable("Helps");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.HelpCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HelpCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Соціальна допомога"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Допомога по працевлаштуванню"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Медична допомога"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Психологічна допомога"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Юридична допомога"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Фінансова допомога"
                        });
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.JobApplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.JobApplicationsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobApplicationsType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кухар"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Поліцейський"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сушист"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Далекобійник"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Продавець-консультант"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Дизайнер"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Програміст"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Танцівщиця"
                        });
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.ProposedJobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("UsersWithProposalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("UsersWithProposalId");

                    b.ToTable("ProposedJobApplication");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gachi.com",
                            Login = "admin",
                            Name = "Михайло",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Patronym = "Петрович",
                            Role = (byte)2,
                            Surname = "Зубенко"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tetiana@gachi.com",
                            Login = "tetiana",
                            Name = "Тетяна",
                            PasswordHash = "6CspveltJTmkFUyGQHoHoSqEUONXJxl9gfpqB0e3dRY=",
                            Patronym = "Ярославівна",
                            Role = (byte)1,
                            Surname = "Дякун"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jamal@gachi.com",
                            Login = "jamal",
                            Name = "Джамал",
                            PasswordHash = "V7RyvfLPlnqKm4YnF74M/M1SYBIYIwdsm803Yr8aAJY=",
                            Patronym = "Сільвестрович",
                            Role = (byte)1,
                            Surname = "Сталоне"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mykola@gachi.com",
                            Login = "mykola",
                            Name = "Микола",
                            PasswordHash = "wc+AFYFvnpXjMPddFzv5dQFcttUDH8g7/RuSoVZrTVQ=",
                            Patronym = "Олегович",
                            Role = (byte)0,
                            Surname = "Гірний"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ivan@gachi.com",
                            Login = "ivan",
                            Name = "Іван",
                            PasswordHash = "zQuUUvw3b8TDWmAIezZvcNiD/JAVJNrx8SL70xk4T2o=",
                            Patronym = "Ігорович",
                            Role = (byte)0,
                            Surname = "Янович"
                        },
                        new
                        {
                            Id = 6,
                            Email = "olexandr@gachi.com",
                            Login = "olexandr",
                            Name = "Олександр",
                            PasswordHash = "aTT/kX//SexsFTyQKnOqTrvI9/0DR/Tw/KMJnwOkfok=",
                            Patronym = "Юрійович",
                            Role = (byte)0,
                            Surname = "Білан"
                        },
                        new
                        {
                            Id = 7,
                            Email = "vitaliy@gachi.com",
                            Login = "vitaliy",
                            Name = "Віталій",
                            PasswordHash = "RGyTMh1A9dYEEPWj0vaLAitmPM5pmywYrJ7y7zoY6MY=",
                            Patronym = "Олегович",
                            Role = (byte)0,
                            Surname = "Кіндрат"
                        },
                        new
                        {
                            Id = 8,
                            Email = "F91F0532-5205-6D4B-9D44-B0B5ED664182@gachi.com",
                            Login = "F91F0532-5205-6D4B-9D44-B0B5ED664182",
                            Name = "Костянтин",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Артемович",
                            Role = (byte)0,
                            Surname = "Теплицький"
                        },
                        new
                        {
                            Id = 9,
                            Email = "9BCBE1F9-10F8-5D12-2A8C-9B7F6D117881@gachi.com",
                            Login = "9BCBE1F9-10F8-5D12-2A8C-9B7F6D117881",
                            Name = "Федір",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Сарматович",
                            Role = (byte)0,
                            Surname = "Троцюк"
                        },
                        new
                        {
                            Id = 10,
                            Email = "8EEC0E45-437E-0E5F-A544-6A17581090CF@gachi.com",
                            Login = "8EEC0E45-437E-0E5F-A544-6A17581090CF",
                            Name = "Далібор",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Тарасович",
                            Role = (byte)0,
                            Surname = "Найдьонов"
                        },
                        new
                        {
                            Id = 11,
                            Email = "6048AC32-A77E-4E8A-61F0-32DC6A83053C@gachi.com",
                            Login = "6048AC32-A77E-4E8A-61F0-32DC6A83053C",
                            Name = "Бративой",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Фролович",
                            Role = (byte)0,
                            Surname = "Стахів"
                        },
                        new
                        {
                            Id = 12,
                            Email = "8C07AE86-0FB2-5733-448B-5B8E2F755EC5@gachi.com",
                            Login = "8C07AE86-0FB2-5733-448B-5B8E2F755EC5",
                            Name = "Аскольд",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Тихонович",
                            Role = (byte)0,
                            Surname = "Фешовець"
                        },
                        new
                        {
                            Id = 13,
                            Email = "2D3979D2-6209-0580-2A38-A210A0643804@gachi.com",
                            Login = "2D3979D2-6209-0580-2A38-A210A0643804",
                            Name = "Вукол",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Тимурович",
                            Role = (byte)0,
                            Surname = "Гуляницький"
                        },
                        new
                        {
                            Id = 14,
                            Email = "8A48AEF7-51C1-6D83-A312-93E1DDCF0450@gachi.com",
                            Login = "8A48AEF7-51C1-6D83-A312-93E1DDCF0450",
                            Name = "Цвітан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Зорянович",
                            Role = (byte)0,
                            Surname = "Малишко"
                        },
                        new
                        {
                            Id = 15,
                            Email = "1674085B-2D68-9D72-9310-F9F493120FDF@gachi.com",
                            Login = "1674085B-2D68-9D72-9310-F9F493120FDF",
                            Name = "Щастислав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Світанович",
                            Role = (byte)0,
                            Surname = "Плішка"
                        },
                        new
                        {
                            Id = 16,
                            Email = "12872033-7D35-0B9F-12A4-C0EC32159379@gachi.com",
                            Login = "12872033-7D35-0B9F-12A4-C0EC32159379",
                            Name = "Доброслав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Любомирович",
                            Role = (byte)0,
                            Surname = "Косар"
                        },
                        new
                        {
                            Id = 17,
                            Email = "7E086B8B-9EE3-69F5-0E39-ABCAD39588D0@gachi.com",
                            Login = "7E086B8B-9EE3-69F5-0E39-ABCAD39588D0",
                            Name = "Євлампій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Вадимович",
                            Role = (byte)0,
                            Surname = "Ангелович"
                        },
                        new
                        {
                            Id = 18,
                            Email = "5DD9E18B-6DCB-86FB-5142-7C33B37A0B65@gachi.com",
                            Login = "5DD9E18B-6DCB-86FB-5142-7C33B37A0B65",
                            Name = "Чара",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Світанович",
                            Role = (byte)0,
                            Surname = "Степченко"
                        },
                        new
                        {
                            Id = 19,
                            Email = "80BE8251-9489-51B8-3414-CD5FC70A477D@gachi.com",
                            Login = "80BE8251-9489-51B8-3414-CD5FC70A477D",
                            Name = "Юхим",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Макарович",
                            Role = (byte)0,
                            Surname = "Герасимець"
                        },
                        new
                        {
                            Id = 20,
                            Email = "F59689BA-56C5-0B92-7896-D68837926157@gachi.com",
                            Login = "F59689BA-56C5-0B92-7896-D68837926157",
                            Name = "Любослав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Азарович",
                            Role = (byte)0,
                            Surname = "Рябоконь"
                        },
                        new
                        {
                            Id = 21,
                            Email = "A944A5A3-3E6C-2B8B-8CBC-A4D1DAEF4DCF@gachi.com",
                            Login = "A944A5A3-3E6C-2B8B-8CBC-A4D1DAEF4DCF",
                            Name = "Юхим",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Юліанович",
                            Role = (byte)0,
                            Surname = "Біленко"
                        },
                        new
                        {
                            Id = 22,
                            Email = "49AF543C-1068-7AFE-1268-0877F91B541B@gachi.com",
                            Login = "49AF543C-1068-7AFE-1268-0877F91B541B",
                            Name = "Щастибог",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Вітанович",
                            Role = (byte)0,
                            Surname = "Семеніхін"
                        },
                        new
                        {
                            Id = 23,
                            Email = "DEDFD2F7-48CA-5E1C-5B79-29B8073518C9@gachi.com",
                            Login = "DEDFD2F7-48CA-5E1C-5B79-29B8073518C9",
                            Name = "Йонас",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Тихонович",
                            Role = (byte)0,
                            Surname = "Собко"
                        },
                        new
                        {
                            Id = 24,
                            Email = "97DDDEC4-7F0F-0BAA-A2CD-7F211ED7A1A1@gachi.com",
                            Login = "97DDDEC4-7F0F-0BAA-A2CD-7F211ED7A1A1",
                            Name = "Хвала",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Адріанович",
                            Role = (byte)0,
                            Surname = "Гопкало"
                        },
                        new
                        {
                            Id = 25,
                            Email = "BD93B82F-678B-A39D-4E65-3B9072546594@gachi.com",
                            Login = "BD93B82F-678B-A39D-4E65-3B9072546594",
                            Name = "Троян",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Сарматович",
                            Role = (byte)0,
                            Surname = "Кравчик"
                        },
                        new
                        {
                            Id = 26,
                            Email = "D0B7A913-1475-8EE6-1895-D4A0B0A85EB0@gachi.com",
                            Login = "D0B7A913-1475-8EE6-1895-D4A0B0A85EB0",
                            Name = "Сергій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Найденович",
                            Role = (byte)0,
                            Surname = "Ясинський"
                        },
                        new
                        {
                            Id = 27,
                            Email = "9EF2DDF3-022A-071D-6E9B-24AA2B0F6824@gachi.com",
                            Login = "9EF2DDF3-022A-071D-6E9B-24AA2B0F6824",
                            Name = "Йомер",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Арсенович",
                            Role = (byte)0,
                            Surname = "Андрущенко"
                        },
                        new
                        {
                            Id = 28,
                            Email = "14CEC370-96FA-1698-5639-91FE3E9C18F9@gachi.com",
                            Login = "14CEC370-96FA-1698-5639-91FE3E9C18F9",
                            Name = "Уличан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Ярославович",
                            Role = (byte)0,
                            Surname = "Авратинський"
                        },
                        new
                        {
                            Id = 29,
                            Email = "010CD3CA-4CD0-0501-8793-4E91C54E877E@gachi.com",
                            Login = "010CD3CA-4CD0-0501-8793-4E91C54E877E",
                            Name = "Еразм",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Жданович",
                            Role = (byte)0,
                            Surname = "Євтушенко"
                        },
                        new
                        {
                            Id = 30,
                            Email = "83791907-0C0C-3525-4716-56458101139B@gachi.com",
                            Login = "83791907-0C0C-3525-4716-56458101139B",
                            Name = "Йосеф",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Милославович",
                            Role = (byte)0,
                            Surname = "Ємельяненко"
                        },
                        new
                        {
                            Id = 31,
                            Email = "B79D280F-49BF-32E7-6BF1-C664BF1C5522@gachi.com",
                            Login = "B79D280F-49BF-32E7-6BF1-C664BF1C5522",
                            Name = "Артем",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Володимирович",
                            Role = (byte)0,
                            Surname = "Невінчаний"
                        },
                        new
                        {
                            Id = 32,
                            Email = "89747AA0-3698-44E9-68D0-3499B0142687@gachi.com",
                            Login = "89747AA0-3698-44E9-68D0-3499B0142687",
                            Name = "Братислав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Богданович",
                            Role = (byte)0,
                            Surname = "Чехівський"
                        },
                        new
                        {
                            Id = 33,
                            Email = "31949148-2468-32F8-21B7-F088FD1991A4@gachi.com",
                            Login = "31949148-2468-32F8-21B7-F088FD1991A4",
                            Name = "Яртур",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Юліанович",
                            Role = (byte)0,
                            Surname = "Медведюк"
                        },
                        new
                        {
                            Id = 34,
                            Email = "6901625F-A02D-6095-3C87-C917F7917680@gachi.com",
                            Login = "6901625F-A02D-6095-3C87-C917F7917680",
                            Name = "Осемрит",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Яромирович",
                            Role = (byte)0,
                            Surname = "Кузьма"
                        },
                        new
                        {
                            Id = 35,
                            Email = "1D670A89-1520-0B85-57BB-42FAE98A9FDD@gachi.com",
                            Login = "1D670A89-1520-0B85-57BB-42FAE98A9FDD",
                            Name = "Федір",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Левович",
                            Role = (byte)0,
                            Surname = "Підгаєцький"
                        },
                        new
                        {
                            Id = 36,
                            Email = "C3071F09-2011-098B-909D-D44B6D5E38F6@gachi.com",
                            Login = "C3071F09-2011-098B-909D-D44B6D5E38F6",
                            Name = "Родослав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Федорович",
                            Role = (byte)0,
                            Surname = "Пашко"
                        },
                        new
                        {
                            Id = 37,
                            Email = "7ACD243A-8B73-85AD-3181-5C1EED002DAA@gachi.com",
                            Login = "7ACD243A-8B73-85AD-3181-5C1EED002DAA",
                            Name = "Живослав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Северинович",
                            Role = (byte)0,
                            Surname = "Канішевський"
                        },
                        new
                        {
                            Id = 38,
                            Email = "72547C4E-9C3C-966E-654A-14CFE7805294@gachi.com",
                            Login = "72547C4E-9C3C-966E-654A-14CFE7805294",
                            Name = "Миробог",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Тихонович",
                            Role = (byte)0,
                            Surname = "Арсенич"
                        },
                        new
                        {
                            Id = 39,
                            Email = "2F9054BA-570A-109A-5C1D-BF1EF5554C41@gachi.com",
                            Login = "2F9054BA-570A-109A-5C1D-BF1EF5554C41",
                            Name = "Драган",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Любомирович",
                            Role = (byte)0,
                            Surname = "Корольчук"
                        },
                        new
                        {
                            Id = 40,
                            Email = "659EC371-7A57-910D-9D99-DE95E1433E19@gachi.com",
                            Login = "659EC371-7A57-910D-9D99-DE95E1433E19",
                            Name = "Хотян",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Мстиславович",
                            Role = (byte)0,
                            Surname = "Полотай"
                        },
                        new
                        {
                            Id = 41,
                            Email = "F6372D04-740C-1F6B-43EF-A1C5440A41CC@gachi.com",
                            Login = "F6372D04-740C-1F6B-43EF-A1C5440A41CC",
                            Name = "Життєлюб",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Остапович",
                            Role = (byte)0,
                            Surname = "Могиленко"
                        },
                        new
                        {
                            Id = 42,
                            Email = "3E20B44A-1E80-4BDA-725A-6BE50C069549@gachi.com",
                            Login = "3E20B44A-1E80-4BDA-725A-6BE50C069549",
                            Name = "Анісій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Ростиславович",
                            Role = (byte)0,
                            Surname = "Пащук"
                        },
                        new
                        {
                            Id = 43,
                            Email = "8414ED38-1EC0-883E-25BB-E14100613A9C@gachi.com",
                            Login = "8414ED38-1EC0-883E-25BB-E14100613A9C",
                            Name = "Йомер",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Антонович",
                            Role = (byte)0,
                            Surname = "Щурат"
                        },
                        new
                        {
                            Id = 44,
                            Email = "2F786E5F-3D2F-5D67-5005-7E2573EFA509@gachi.com",
                            Login = "2F786E5F-3D2F-5D67-5005-7E2573EFA509",
                            Name = "Микита",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Федорович",
                            Role = (byte)0,
                            Surname = "Роднянський"
                        },
                        new
                        {
                            Id = 45,
                            Email = "FF8DF46E-2C26-0C72-7FCB-3AAAD2426C11@gachi.com",
                            Login = "FF8DF46E-2C26-0C72-7FCB-3AAAD2426C11",
                            Name = "Щедрогост",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Макарович",
                            Role = (byte)0,
                            Surname = "Хмелецький"
                        },
                        new
                        {
                            Id = 46,
                            Email = "E4D2BCD0-9C9F-9F10-359E-F4ADCFE20652@gachi.com",
                            Login = "E4D2BCD0-9C9F-9F10-359E-F4ADCFE20652",
                            Name = "Данко",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Августинович",
                            Role = (byte)0,
                            Surname = "Авдієвський"
                        },
                        new
                        {
                            Id = 47,
                            Email = "1D747F30-52F4-1EA1-0D6C-766458B68580@gachi.com",
                            Login = "1D747F30-52F4-1EA1-0D6C-766458B68580",
                            Name = "Хранимир",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Орестович",
                            Role = (byte)0,
                            Surname = "Калениченко"
                        },
                        new
                        {
                            Id = 48,
                            Email = "11311BAB-012E-220F-4FF9-82A3703B2B2B@gachi.com",
                            Login = "11311BAB-012E-220F-4FF9-82A3703B2B2B",
                            Name = "Корнелій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Вадимович",
                            Role = (byte)0,
                            Surname = "Оніщенко"
                        },
                        new
                        {
                            Id = 49,
                            Email = "AE0FDEC6-629A-67B7-0E32-B30B3B818203@gachi.com",
                            Login = "AE0FDEC6-629A-67B7-0E32-B30B3B818203",
                            Name = "Хранимир",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Чеславович",
                            Role = (byte)0,
                            Surname = "Батенко"
                        },
                        new
                        {
                            Id = 50,
                            Email = "9CB37CF8-365D-0E5B-7B60-0C5C5F4B0227@gachi.com",
                            Login = "9CB37CF8-365D-0E5B-7B60-0C5C5F4B0227",
                            Name = "Радан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Юліанович",
                            Role = (byte)0,
                            Surname = "Зазуляк"
                        },
                        new
                        {
                            Id = 51,
                            Email = "D156F22F-66F4-01C0-0BF0-887E2C574A13@gachi.com",
                            Login = "D156F22F-66F4-01C0-0BF0-887E2C574A13",
                            Name = "Дорофій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Юхимович",
                            Role = (byte)0,
                            Surname = "Крамськой"
                        },
                        new
                        {
                            Id = 52,
                            Email = "BB41BAAF-78FA-295B-4584-3470A1F14BBF@gachi.com",
                            Login = "BB41BAAF-78FA-295B-4584-3470A1F14BBF",
                            Name = "Щедрогост",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Леонідович",
                            Role = (byte)0,
                            Surname = "Громики"
                        },
                        new
                        {
                            Id = 53,
                            Email = "2B92A1B7-6AC4-6587-4EE1-C62620DC04CD@gachi.com",
                            Login = "2B92A1B7-6AC4-6587-4EE1-C62620DC04CD",
                            Name = "Ничипір",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Никодимович",
                            Role = (byte)0,
                            Surname = "Кайда"
                        },
                        new
                        {
                            Id = 54,
                            Email = "B5A7111A-375B-8633-033F-0CE94AD283C7@gachi.com",
                            Login = "B5A7111A-375B-8633-033F-0CE94AD283C7",
                            Name = "Еміль",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Пилипович",
                            Role = (byte)0,
                            Surname = "Денисенко"
                        },
                        new
                        {
                            Id = 55,
                            Email = "CFF82BCF-63DA-9799-6638-A9C3077AA70F@gachi.com",
                            Login = "CFF82BCF-63DA-9799-6638-A9C3077AA70F",
                            Name = "Юліан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Левович",
                            Role = (byte)0,
                            Surname = "Манзій"
                        },
                        new
                        {
                            Id = 56,
                            Email = "A4CA4802-348A-65E2-2B81-8E87F5E51FFB@gachi.com",
                            Login = "A4CA4802-348A-65E2-2B81-8E87F5E51FFB",
                            Name = "Адріан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Зорянович",
                            Role = (byte)0,
                            Surname = "Марченко"
                        },
                        new
                        {
                            Id = 57,
                            Email = "5B057869-59E5-777D-9EEA-C517C7B31C7D@gachi.com",
                            Login = "5B057869-59E5-777D-9EEA-C517C7B31C7D",
                            Name = "Києслав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Йосипович",
                            Role = (byte)0,
                            Surname = "Витвицький"
                        },
                        new
                        {
                            Id = 58,
                            Email = "47B22C1A-0F6C-8C7D-937F-A7841EA55DC7@gachi.com",
                            Login = "47B22C1A-0F6C-8C7D-937F-A7841EA55DC7",
                            Name = "Єгор",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Устимович",
                            Role = (byte)0,
                            Surname = "Петрусь"
                        },
                        new
                        {
                            Id = 59,
                            Email = "5AF954E2-2190-09A9-943C-4BF38BE8814A@gachi.com",
                            Login = "5AF954E2-2190-09A9-943C-4BF38BE8814A",
                            Name = "Добривод",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Тимурович",
                            Role = (byte)0,
                            Surname = "Галаса"
                        },
                        new
                        {
                            Id = 60,
                            Email = "3B90E239-72E4-7106-9B81-3A79A1044C55@gachi.com",
                            Login = "3B90E239-72E4-7106-9B81-3A79A1044C55",
                            Name = "Колодій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Драганович",
                            Role = (byte)0,
                            Surname = "Прудіус"
                        },
                        new
                        {
                            Id = 61,
                            Email = "665709BC-4BDB-0CAA-956D-34B529070270@gachi.com",
                            Login = "665709BC-4BDB-0CAA-956D-34B529070270",
                            Name = "Наслав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Адамович",
                            Role = (byte)0,
                            Surname = "Канішевський"
                        },
                        new
                        {
                            Id = 62,
                            Email = "50965BC6-94FF-78DE-5D8F-9403FBE73741@gachi.com",
                            Login = "50965BC6-94FF-78DE-5D8F-9403FBE73741",
                            Name = "Панас",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Северинович",
                            Role = (byte)0,
                            Surname = "Гриньків"
                        },
                        new
                        {
                            Id = 63,
                            Email = "5D68CD80-0B90-1320-2290-84ED50AB0FF7@gachi.com",
                            Login = "5D68CD80-0B90-1320-2290-84ED50AB0FF7",
                            Name = "Щедрогост",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Тихонович",
                            Role = (byte)0,
                            Surname = "Костюк"
                        },
                        new
                        {
                            Id = 64,
                            Email = "25D65028-2C8D-2BDE-6CE0-B7F48F022D31@gachi.com",
                            Login = "25D65028-2C8D-2BDE-6CE0-B7F48F022D31",
                            Name = "Недан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Сарматович",
                            Role = (byte)0,
                            Surname = "Ткач"
                        },
                        new
                        {
                            Id = 65,
                            Email = "A8A17287-0221-7CA2-9C33-E1590B1E1364@gachi.com",
                            Login = "A8A17287-0221-7CA2-9C33-E1590B1E1364",
                            Name = "Малик",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Вікторович",
                            Role = (byte)0,
                            Surname = "Стець"
                        },
                        new
                        {
                            Id = 66,
                            Email = "DBCF2ACA-27F5-12AC-376B-23C3447494FE@gachi.com",
                            Login = "DBCF2ACA-27F5-12AC-376B-23C3447494FE",
                            Name = "Любим",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Макарович",
                            Role = (byte)0,
                            Surname = "Гомоляка"
                        },
                        new
                        {
                            Id = 67,
                            Email = "5A6D5CD4-2298-9D0E-8868-207977E4501A@gachi.com",
                            Login = "5A6D5CD4-2298-9D0E-8868-207977E4501A",
                            Name = "Ліпослав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Герасимович",
                            Role = (byte)0,
                            Surname = "Циба"
                        },
                        new
                        {
                            Id = 68,
                            Email = "81928FB8-83B6-0DAF-7488-703D099B19FB@gachi.com",
                            Login = "81928FB8-83B6-0DAF-7488-703D099B19FB",
                            Name = "Боримир",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Остапович",
                            Role = (byte)0,
                            Surname = "Прилуцький"
                        },
                        new
                        {
                            Id = 69,
                            Email = "7B3E0D13-7863-94A7-0A91-6ED740830198@gachi.com",
                            Login = "7B3E0D13-7863-94A7-0A91-6ED740830198",
                            Name = "Іоанн",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Арсенович",
                            Role = (byte)0,
                            Surname = "Бараник"
                        },
                        new
                        {
                            Id = 70,
                            Email = "CD78B3E4-5749-5D7D-A51C-0BFB856E97C6@gachi.com",
                            Login = "CD78B3E4-5749-5D7D-A51C-0BFB856E97C6",
                            Name = "Май",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Орестович",
                            Role = (byte)0,
                            Surname = "Устиянович"
                        },
                        new
                        {
                            Id = 71,
                            Email = "D37EB513-3AFA-96F9-1DD2-507C6F47976E@gachi.com",
                            Login = "D37EB513-3AFA-96F9-1DD2-507C6F47976E",
                            Name = "Осмомисл",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Борисович",
                            Role = (byte)0,
                            Surname = "Андрійченко"
                        },
                        new
                        {
                            Id = 72,
                            Email = "2E59C76F-0A87-7043-2578-C16164CD4577@gachi.com",
                            Login = "2E59C76F-0A87-7043-2578-C16164CD4577",
                            Name = "Власт",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Семенович",
                            Role = (byte)0,
                            Surname = "Ситенко"
                        },
                        new
                        {
                            Id = 73,
                            Email = "E65BEB85-82F8-10B7-99C3-D1542F095D1A@gachi.com",
                            Login = "E65BEB85-82F8-10B7-99C3-D1542F095D1A",
                            Name = "Ладислав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Никодимович",
                            Role = (byte)0,
                            Surname = "Мізецький"
                        },
                        new
                        {
                            Id = 74,
                            Email = "B2638CE9-30F3-33D3-1808-083DF903745E@gachi.com",
                            Login = "B2638CE9-30F3-33D3-1808-083DF903745E",
                            Name = "Щастибог",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Олегович",
                            Role = (byte)0,
                            Surname = "Кованько"
                        },
                        new
                        {
                            Id = 75,
                            Email = "B125252E-36B8-6944-691A-A1B2A1DE56DE@gachi.com",
                            Login = "B125252E-36B8-6944-691A-A1B2A1DE56DE",
                            Name = "Ярило",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Максимович",
                            Role = (byte)0,
                            Surname = "Юцевич"
                        },
                        new
                        {
                            Id = 76,
                            Email = "FCBE6D38-6528-532B-16DC-4F127E821F29@gachi.com",
                            Login = "FCBE6D38-6528-532B-16DC-4F127E821F29",
                            Name = "Єремій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Федорович",
                            Role = (byte)0,
                            Surname = "Лагодовський"
                        },
                        new
                        {
                            Id = 77,
                            Email = "B3F92BF8-35CC-69B4-9B53-FE7D183A07BF@gachi.com",
                            Login = "B3F92BF8-35CC-69B4-9B53-FE7D183A07BF",
                            Name = "Дантур",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Добромирович",
                            Role = (byte)0,
                            Surname = "Коновалюк"
                        },
                        new
                        {
                            Id = 78,
                            Email = "DD503B0D-7537-4A41-6535-1BC2BC827DF8@gachi.com",
                            Login = "DD503B0D-7537-4A41-6535-1BC2BC827DF8",
                            Name = "Грива",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Соломонович",
                            Role = (byte)0,
                            Surname = "Ярошенко"
                        },
                        new
                        {
                            Id = 79,
                            Email = "E6825126-5B80-33E2-2CD9-FFDFBA88A611@gachi.com",
                            Login = "E6825126-5B80-33E2-2CD9-FFDFBA88A611",
                            Name = "Віст",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Максимович",
                            Role = (byte)0,
                            Surname = "Коробко"
                        },
                        new
                        {
                            Id = 80,
                            Email = "C1136E3F-379E-277D-8ADA-40F947F407EE@gachi.com",
                            Login = "C1136E3F-379E-277D-8ADA-40F947F407EE",
                            Name = "Русан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Северинович",
                            Role = (byte)0,
                            Surname = "Адамовський"
                        },
                        new
                        {
                            Id = 81,
                            Email = "E6C92451-0D5B-6F8D-5DD0-DC807F9672FA@gachi.com",
                            Login = "E6C92451-0D5B-6F8D-5DD0-DC807F9672FA",
                            Name = "Любодар",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Найденович",
                            Role = (byte)0,
                            Surname = "Коморовський"
                        },
                        new
                        {
                            Id = 82,
                            Email = "D6708551-24E8-5202-270A-3B4FB4D41B33@gachi.com",
                            Login = "D6708551-24E8-5202-270A-3B4FB4D41B33",
                            Name = "Добролик",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Мстиславович",
                            Role = (byte)0,
                            Surname = "Пантелюк"
                        },
                        new
                        {
                            Id = 83,
                            Email = "8DF98409-7128-1E63-9A60-41D4AF585749@gachi.com",
                            Login = "8DF98409-7128-1E63-9A60-41D4AF585749",
                            Name = "Йошка",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Фролович",
                            Role = (byte)0,
                            Surname = "Дудка"
                        },
                        new
                        {
                            Id = 84,
                            Email = "09433710-7303-0006-4197-9955C6108A28@gachi.com",
                            Login = "09433710-7303-0006-4197-9955C6108A28",
                            Name = "Жито",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Семенович",
                            Role = (byte)0,
                            Surname = "Архипенко"
                        },
                        new
                        {
                            Id = 85,
                            Email = "AC912483-1D26-0AB4-723E-51A5628B131E@gachi.com",
                            Login = "AC912483-1D26-0AB4-723E-51A5628B131E",
                            Name = "Назарій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Радимович",
                            Role = (byte)0,
                            Surname = "Моравський"
                        },
                        new
                        {
                            Id = 86,
                            Email = "A7918CE5-6432-8BEA-99F0-3AD624A72A9A@gachi.com",
                            Login = "A7918CE5-6432-8BEA-99F0-3AD624A72A9A",
                            Name = "Жито",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Герасимович",
                            Role = (byte)0,
                            Surname = "Сенюк"
                        },
                        new
                        {
                            Id = 87,
                            Email = "2A178135-4A29-36D1-34E1-B258CBCF65C1@gachi.com",
                            Login = "2A178135-4A29-36D1-34E1-B258CBCF65C1",
                            Name = "Іоанн",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Романович",
                            Role = (byte)0,
                            Surname = "Татарнюк"
                        },
                        new
                        {
                            Id = 88,
                            Email = "3E07DBD0-2E94-46EF-6F1F-8E634324A750@gachi.com",
                            Login = "3E07DBD0-2E94-46EF-6F1F-8E634324A750",
                            Name = "Надій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Арсенович",
                            Role = (byte)0,
                            Surname = "Корчинський"
                        },
                        new
                        {
                            Id = 89,
                            Email = "1964A89F-8B68-81FA-5A19-3E8D7E604C09@gachi.com",
                            Login = "1964A89F-8B68-81FA-5A19-3E8D7E604C09",
                            Name = "Немир",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Арсенович",
                            Role = (byte)0,
                            Surname = "Галущинський"
                        },
                        new
                        {
                            Id = 90,
                            Email = "7ED017FC-078A-5A37-6BD9-F11D6A6E0ED3@gachi.com",
                            Login = "7ED017FC-078A-5A37-6BD9-F11D6A6E0ED3",
                            Name = "Колодій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Полянович",
                            Role = (byte)0,
                            Surname = "Веремій"
                        },
                        new
                        {
                            Id = 91,
                            Email = "D5733038-75B9-6CFC-14BE-45E7D2F52536@gachi.com",
                            Login = "D5733038-75B9-6CFC-14BE-45E7D2F52536",
                            Name = "Милодух",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Добромирович",
                            Role = (byte)0,
                            Surname = "Костогриз"
                        },
                        new
                        {
                            Id = 92,
                            Email = "0304531E-90C3-9C8D-4AC5-D1F0FAFD0CBB@gachi.com",
                            Login = "0304531E-90C3-9C8D-4AC5-D1F0FAFD0CBB",
                            Name = "Уличан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Вітанович",
                            Role = (byte)0,
                            Surname = "Охримович"
                        },
                        new
                        {
                            Id = 93,
                            Email = "F944CB15-2500-6CD5-01E9-AAB7C1C37CC1@gachi.com",
                            Login = "F944CB15-2500-6CD5-01E9-AAB7C1C37CC1",
                            Name = "Юхим",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Радимович",
                            Role = (byte)0,
                            Surname = "Оробець"
                        },
                        new
                        {
                            Id = 94,
                            Email = "CF73E0E7-70D8-27F2-2C98-96971EA431DD@gachi.com",
                            Login = "CF73E0E7-70D8-27F2-2C98-96971EA431DD",
                            Name = "Світовид",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Семенович",
                            Role = (byte)0,
                            Surname = "Лісовий"
                        },
                        new
                        {
                            Id = 95,
                            Email = "0C3787AB-5A5D-570E-04AE-E28714A219F5@gachi.com",
                            Login = "0C3787AB-5A5D-570E-04AE-E28714A219F5",
                            Name = "Біловид",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Семенович",
                            Role = (byte)0,
                            Surname = "Гончарук"
                        },
                        new
                        {
                            Id = 96,
                            Email = "423FA339-824D-09CC-659E-8C3558037A74@gachi.com",
                            Login = "423FA339-824D-09CC-659E-8C3558037A74",
                            Name = "Цвітан",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Сарматович",
                            Role = (byte)0,
                            Surname = "Крижицький"
                        },
                        new
                        {
                            Id = 97,
                            Email = "6FEEC903-3FCF-3FB7-9AC1-2BF684F662C0@gachi.com",
                            Login = "6FEEC903-3FCF-3FB7-9AC1-2BF684F662C0",
                            Name = "Ян",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Антонович",
                            Role = (byte)0,
                            Surname = "Кирпань"
                        },
                        new
                        {
                            Id = 98,
                            Email = "99FC3F40-2E84-67D2-A50E-FAC99B6F91AE@gachi.com",
                            Login = "99FC3F40-2E84-67D2-A50E-FAC99B6F91AE",
                            Name = "Щастислав",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Максимович",
                            Role = (byte)0,
                            Surname = "Перебийніс"
                        },
                        new
                        {
                            Id = 99,
                            Email = "1533680A-7613-498F-2B1F-EFE88D0F8602@gachi.com",
                            Login = "1533680A-7613-498F-2B1F-EFE88D0F8602",
                            Name = "Єгор",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Фролович",
                            Role = (byte)0,
                            Surname = "Черкасенко"
                        },
                        new
                        {
                            Id = 100,
                            Email = "675C2EFE-4096-9B8A-7839-CEA053D61595@gachi.com",
                            Login = "675C2EFE-4096-9B8A-7839-CEA053D61595",
                            Name = "Тиміш",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Олегович",
                            Role = (byte)0,
                            Surname = "Загребельний"
                        },
                        new
                        {
                            Id = 101,
                            Email = "529526F7-46E1-52F4-9B17-94365A9121E2@gachi.com",
                            Login = "529526F7-46E1-52F4-9B17-94365A9121E2",
                            Name = "Гервасій",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Йосипович",
                            Role = (byte)0,
                            Surname = "Маринченко"
                        },
                        new
                        {
                            Id = 102,
                            Email = "4C8D17D2-A52A-3789-0201-740B8A4F0B6C@gachi.com",
                            Login = "4C8D17D2-A52A-3789-0201-740B8A4F0B6C",
                            Name = "Флор",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Милославович",
                            Role = (byte)0,
                            Surname = "Миронюк"
                        },
                        new
                        {
                            Id = 103,
                            Email = "60E10532-128F-236E-8098-6CAC90331750@gachi.com",
                            Login = "60E10532-128F-236E-8098-6CAC90331750",
                            Name = "Єгор",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Зорянович",
                            Role = (byte)0,
                            Surname = "Чучупак"
                        },
                        new
                        {
                            Id = 104,
                            Email = "8595E699-02B4-6EA5-4AF4-3D1764741C6A@gachi.com",
                            Login = "8595E699-02B4-6EA5-4AF4-3D1764741C6A",
                            Name = "Магадар",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Ростиславович",
                            Role = (byte)0,
                            Surname = "Чубатенко"
                        },
                        new
                        {
                            Id = 105,
                            Email = "F699076B-9EC2-2BFF-3063-38FEEF9D9536@gachi.com",
                            Login = "F699076B-9EC2-2BFF-3063-38FEEF9D9536",
                            Name = "Щедрогост",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Захарович",
                            Role = (byte)0,
                            Surname = "Гайденко"
                        },
                        new
                        {
                            Id = 106,
                            Email = "226F839A-05A6-0BF7-2A5D-1759B2B79A0A@gachi.com",
                            Login = "226F839A-05A6-0BF7-2A5D-1759B2B79A0A",
                            Name = "Шерлок",
                            PasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            Patronym = "Арсенович",
                            Role = (byte)0,
                            Surname = "Кормош"
                        });
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.AppliedJobApplication", b =>
                {
                    b.HasOne("GachiHelp.DAL.Entities.User", "AppliedUser")
                        .WithMany("AppliedJobApplication")
                        .HasForeignKey("AppliedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GachiHelp.DAL.Entities.JobApplications", "JobApplication")
                        .WithMany("AppliedJobApplication")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedUser");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.Help", b =>
                {
                    b.HasOne("GachiHelp.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GachiHelp.DAL.Entities.HelpCategory", "HelpCategory")
                        .WithMany()
                        .HasForeignKey("HelpCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("HelpCategory");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.JobApplications", b =>
                {
                    b.HasOne("GachiHelp.DAL.Entities.JobApplicationsType", "ApplicationType")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationType");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.ProposedJobApplication", b =>
                {
                    b.HasOne("GachiHelp.DAL.Entities.JobApplications", "JobApplication")
                        .WithMany("ProposedJobApplication")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GachiHelp.DAL.Entities.User", "UsersWithProposal")
                        .WithMany("ProposedJobApplication")
                        .HasForeignKey("UsersWithProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("UsersWithProposal");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.JobApplications", b =>
                {
                    b.Navigation("AppliedJobApplication");

                    b.Navigation("ProposedJobApplication");
                });

            modelBuilder.Entity("GachiHelp.DAL.Entities.User", b =>
                {
                    b.Navigation("AppliedJobApplication");

                    b.Navigation("ProposedJobApplication");
                });
#pragma warning restore 612, 618
        }
    }
}
