// <auto-generated />
using GachiHelp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GachiHelp.WebApi.Migrations
{
    [DbContext(typeof(GachiContext))]
    [Migration("20221110172033_AddedUserData")]
    partial class AddedUserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GachiHelp.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gachi.com",
                            Login = "admin",
                            Name = "Михайло",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Patronym = "Петрович",
                            Role = (byte)2,
                            Surname = "Зубенко"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tetiana@gachi.com",
                            Login = "tetiana",
                            Name = "Тетяна",
                            PasswordHash = "6CspveltJTmkFUyGQHoHoSqEUONXJxl9gfpqB0e3dRY=",
                            Patronym = "Ярославівна",
                            Role = (byte)1,
                            Surname = "Дякун"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jamal@gachi.com",
                            Login = "jamal",
                            Name = "Джамал",
                            PasswordHash = "V7RyvfLPlnqKm4YnF74M/M1SYBIYIwdsm803Yr8aAJY=",
                            Patronym = "Сільвестрович",
                            Role = (byte)1,
                            Surname = "Сталоне"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mykola@gachi.com",
                            Login = "mykola",
                            Name = "Микола",
                            PasswordHash = "wc+AFYFvnpXjMPddFzv5dQFcttUDH8g7/RuSoVZrTVQ=",
                            Patronym = "Олегович",
                            Role = (byte)0,
                            Surname = "Гірний"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ivan@gachi.com",
                            Login = "ivan",
                            Name = "Іван",
                            PasswordHash = "zQuUUvw3b8TDWmAIezZvcNiD/JAVJNrx8SL70xk4T2o=",
                            Patronym = "Ігорович",
                            Role = (byte)0,
                            Surname = "Янович"
                        },
                        new
                        {
                            Id = 6,
                            Email = "olexandr@gachi.com",
                            Login = "olexandr",
                            Name = "Олександр",
                            PasswordHash = "aTT/kX//SexsFTyQKnOqTrvI9/0DR/Tw/KMJnwOkfok=",
                            Patronym = "Юрійович",
                            Role = (byte)0,
                            Surname = "Білан"
                        },
                        new
                        {
                            Id = 7,
                            Email = "vitaliy@gachi.com",
                            Login = "vitaliy",
                            Name = "Віталій",
                            PasswordHash = "RGyTMh1A9dYEEPWj0vaLAitmPM5pmywYrJ7y7zoY6MY=",
                            Patronym = "Олегович",
                            Role = (byte)0,
                            Surname = "Кіндрат"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
