// <auto-generated />
using GachiHelp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GachiHelp.WebApi.Migrations
{
    [DbContext(typeof(GachiContext))]
    partial class GachiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GachiHelp.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = (byte)2
                        },
                        new
                        {
                            Id = 2,
                            Login = "tetiana",
                            PasswordHash = "6CspveltJTmkFUyGQHoHoSqEUONXJxl9gfpqB0e3dRY=",
                            Role = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Login = "jamal",
                            PasswordHash = "V7RyvfLPlnqKm4YnF74M/M1SYBIYIwdsm803Yr8aAJY=",
                            Role = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            Login = "mykola",
                            PasswordHash = "wc+AFYFvnpXjMPddFzv5dQFcttUDH8g7/RuSoVZrTVQ=",
                            Role = (byte)2
                        },
                        new
                        {
                            Id = 5,
                            Login = "ivan",
                            PasswordHash = "zQuUUvw3b8TDWmAIezZvcNiD/JAVJNrx8SL70xk4T2o=",
                            Role = (byte)2
                        },
                        new
                        {
                            Id = 6,
                            Login = "olexandr",
                            PasswordHash = "aTT/kX//SexsFTyQKnOqTrvI9/0DR/Tw/KMJnwOkfok=",
                            Role = (byte)2
                        },
                        new
                        {
                            Id = 7,
                            Login = "vitaliy",
                            PasswordHash = "RGyTMh1A9dYEEPWj0vaLAitmPM5pmywYrJ7y7zoY6MY=",
                            Role = (byte)2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
